import React from 'react';

/**
 * PrivacyPolicy Component
 * Renders the full Privacy Policy for Hwan Power using Tailwind CSS.
 * Date: April 10, 2026
 */
const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12  text-gray-800 leading-relaxed">
      <header className="border-b pb-8 mb-8">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 italic">Last updated: April 10, 2026</p>
      </header>

      <section className="mb-8">
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="mb-4">
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      {/* Interpretation and Definitions */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Interpretation and Definitions
        </h2>
        
        <div className="ml-4">
          <h3 className="text-xl font-semibold mb-2 text-gray-900">Interpretation</h3>
          <p className="mb-4">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-xl font-semibold mb-2 text-gray-900">Definitions</h3>
          <p className="mb-4 font-medium italic">For the purposes of this Privacy Policy:</p>
          <ul className="space-y-4 list-none">
            <li>
              <strong className="text-gray-900">Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              <strong className="text-gray-900">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              <strong className="text-gray-900">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Hwan Power, KINFRA Advanced Technology Park Ramanattukara.
            </li>
            <li>
              <strong className="text-gray-900">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              <strong className="text-gray-900">Country</strong> refers to: Kerala, India
            </li>
            <li>
              <strong className="text-gray-900">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
            </li>
            <li>
              <strong className="text-gray-900">Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.
            </li>
            <li>
              <strong className="text-gray-900">Service</strong> refers to the Website.
            </li>
            <li>
              <strong className="text-gray-900">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong className="text-gray-900">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong className="text-gray-900">Website</strong> refers to ww.hwanpower.com, accessible from <a href="https://hwanpower.com/" className="text-yellow-600 hover:underline">https://hwanpower.com/</a>.
            </li>
            <li>
              <strong className="text-gray-900">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>
      </section>

      {/* Collecting and Using Personal Data */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Collecting and Using Your Personal Data
        </h2>
        
        <div className="ml-4">
          <h3 className="text-xl font-semibold mb-3 text-gray-900">Types of Data Collected</h3>
          
          <h4 className="text-lg font-bold mb-2">Personal Data</h4>
          <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside mb-6 space-y-1 ml-4 text-gray-700">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>

          <h4 className="text-lg font-bold mb-2">Usage Data</h4>
          <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <p className="mb-6">We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

          <h4 className="text-lg font-bold mb-2">Tracking Technologies and Cookies</h4>
          <div className="space-y-4">
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
            </ul>
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
            <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            
            <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
              <ul className="space-y-6">
                <li>
                  <p className="font-bold underline">Necessary / Essential Cookies</p>
                  <p className="text-sm">Type: Session Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</p>
                </li>
                <li>
                  <p className="font-bold underline">Cookies Policy / Notice Acceptance Cookies</p>
                  <p className="text-sm">Type: Persistent Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                </li>
                <li>
                  <p className="font-bold underline">Functionality Cookies</p>
                  <p className="text-sm">Type: Persistent Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience.</p>
                </li>
              </ul>
            </div>
            <p className="text-sm italic">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of Our Privacy Policy.</p>
          </div>
        </div>
      </section>

      {/* Use of Your Personal Data */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Use of Your Personal Data
        </h2>
        <div className="ml-4">
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="space-y-3">
            <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications.</li>
            <li><strong>To provide You:</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for data analysis, identifying usage trends, and determining the effectiveness of our promotional campaigns.</li>
          </ul>

          <h3 className="text-xl font-semibold mt-8 mb-4">Sharing Your Personal Data</h3>
          <p className="mb-4">We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service, and to contact You.</li>
            <li><strong>For business transfers:</strong> In connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong>With Affiliates:</strong> We will require those affiliates to honor this Privacy Policy.</li>
            <li><strong>With business partners:</strong> To offer You certain products, services or promotions.</li>
            <li><strong>With other users:</strong> When You share information in public areas, it may be viewed by all users and publicly distributed.</li>
            <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>
        </div>
      </section>

      {/* Retention of Data */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Retention of Your Personal Data
        </h2>
        <div className="ml-4 space-y-4">
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          <p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods ("up to").</p>
          
          <div className="overflow-x-auto">
            <table className="min-w-full bg-white border border-gray-200">
              <thead className="bg-gray-100">
                <tr>
                  <th className="px-4 py-2 border text-left">Category</th>
                  <th className="px-4 py-2 border text-left">Retention Period</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="px-4 py-2 border font-semibold">User Accounts</td>
                  <td className="px-4 py-2 border">Duration of relationship + up to 24 months after closure</td>
                </tr>
                <tr>
                  <td className="px-4 py-2 border font-semibold">Customer Support / Chat</td>
                  <td className="px-4 py-2 border">Up to 24 months from date of closure</td>
                </tr>
                <tr>
                  <td className="px-4 py-2 border font-semibold">Website Analytics / Logs</td>
                  <td className="px-4 py-2 border">Up to 24 months from date of collection</td>
                </tr>
              </tbody>
            </table>
          </div>

          <p>When retention periods expire, We securely delete or anonymize Personal Data via deletion from systems, encrypted backup retention (limited period), or anonymization into statistical data.</p>
        </div>
      </section>

      {/* Transfer and Deletion */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Transfer & Deletion
        </h2>
        <div className="ml-4 space-y-6">
          <div>
            <h3 className="text-xl font-semibold mb-2">Transfer of Your Personal Data</h3>
            <p>Your information is processed at the Company's operating offices and other locations. It may be transferred to computers located outside of Your jurisdiction where data protection laws may differ. The Company will take all steps reasonably necessary to ensure adequate controls are in place.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-2">Delete Your Personal Data</h3>
            <p>You have the right to delete or request assistance in deleting the Personal Data that We have collected. You may update, amend, or delete Your information by signing in to Your Account or contacting Us directly. Note that We may need to retain certain information when we have a legal obligation to do so.</p>
          </div>
        </div>
      </section>

      {/* Disclosure and Security */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Disclosure and Security
        </h2>
        <div className="ml-4 space-y-4">
          <h3 className="text-xl font-semibold">Disclosure of Your Personal Data</h3>
          <p><strong>Business Transactions:</strong> Your Personal Data may be transferred during a merger or asset sale. We will provide notice before this happens.</p>
          <p><strong>Law enforcement:</strong> We may be required to disclose data if required by law or valid requests by public authorities.</p>
          <p><strong>Other legal requirements:</strong> We may disclose data to comply with legal obligations, protect rights/property, prevent wrongdoing, or protect personal safety.</p>
          
          <h3 className="text-xl font-semibold mt-6">Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure. While We strive to use commercially reasonable means to protect Your data, We cannot guarantee its absolute security.</p>
        </div>
      </section>

      {/* Detailed Processing Info */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Detailed Information on Processing
        </h2>
        <div className="ml-4 space-y-4">
          <p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect and process info in accordance with their Privacy Policies.</p>
          <ul className="space-y-4">
            <li className="bg-gray-50 p-4 rounded-md border">
              <strong>Mouseflow:</strong> Session replay and heatmap tool. Operated by ApS. <br />
              <a href="https://mouseflow.com/privacy/" className="text-yellow-600 text-sm">https://mouseflow.com/privacy/</a>
            </li>
            <li className="bg-gray-50 p-4 rounded-md border">
              <strong>FreshDesk:</strong> Customer support software. Operated by Freshworks, Inc. <br />
              <a href="https://www.freshworks.com/privacy/" className="text-yellow-600 text-sm">https://www.freshworks.com/privacy/</a>
            </li>
            <li className="bg-gray-50 p-4 rounded-md border">
              <strong>Google Places:</strong> Information about places via HTTP requests. Operated by Google. <br />
              <a href="https://www.google.com/intl/en/policies/privacy/" className="text-yellow-600 text-sm">https://www.google.com/intl/en/policies/privacy/</a>
            </li>
          </ul>
        </div>
      </section>

      {/* Children's Privacy and Links */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold  pl-4 mb-4 uppercase tracking-wide">
          Other Policies
        </h2>
        <div className="ml-4 space-y-6">
          <div>
            <h3 className="text-xl font-semibold mb-2">Children's Privacy</h3>
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect info from this age group. If we become aware of such collection without parental consent, we take steps to remove it.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-2">Links to Other Websites</h3>
            <p>Our Service may contain links to websites not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We assume no responsibility for third-party content or practices.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-2">Changes to this Privacy Policy</h3>
            <p>We may update Our Privacy Policy from time to time. We will notify You by posting the new policy on this page and letting You know via email or prominent notice prior to changes becoming effective.</p>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <footer className="mt-12 pt-8 border-t border-gray-200">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
        <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
        <p className="font-medium bg-yellow-50 inline-block px-4 py-2 rounded-lg border border-yellow-100">
          By email: <a href="mailto:hwanpowerr@gmail.com" className="text-yellow-700 hover:underline">hwanpowerr@gmail.com</a>
        </p>
      </footer>
    </div>
  );
};

export default PrivacyPolicy;